<div id="welcomeheader" class="navbar-default">
	<div class="container">
		<div class="logo ">
			<a href="<?php echo $so['config']['site_url'];?>"><img src="<?php echo $so['config']['theme_url'];?>/img/logo.<?php echo $so['config']['logo_extension'];?>" alt="Logo"> </a>
		</div>
		<!-- <?php //if ($so['config']['user_registration'] == 1): ?>
			<ul class="nav navbar-nav navbar-right <?php //echo so_RightToLeft('pull-right');?>">
				<li class="absul-right">
					<a class="mdbtn" href="<?php //echo $so['config']['site_url'];?>"><?php //echo $so['lang']['login']?></a>
				</li>
			</ul>
		<?php //endif ?> -->
	</div>
</div>